import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Categories
const CATEGORIES = [
  { name: "Percentages", slug: "percentages", description: "Percentage calculations and shortcuts", displayOrder: 1 },
  { name: "Speed, Distance & Time", slug: "speed-distance-time", description: "Speed, distance, and time problems", displayOrder: 2 },
  { name: "Fractions", slug: "fractions", description: "Fraction operations and comparisons", displayOrder: 3 },
  { name: "Ratios & Proportions", slug: "ratios-proportions", description: "Ratios, proportions, and division", displayOrder: 4 },
  { name: "Profit & Loss", slug: "profit-loss", description: "Profit, loss, discount, and selling price", displayOrder: 5 },
  { name: "Averages", slug: "averages", description: "Average and mean calculations", displayOrder: 6 },
  { name: "Work & Time", slug: "work-time", description: "Man-days and work rate problems", displayOrder: 7 },
  { name: "Pipes & Tanks", slug: "pipes-tanks", description: "Pipe filling and tank problems", displayOrder: 8 },
  { name: "Unit Conversion", slug: "unit-conversion", description: "Unit conversions (km/h to m/s, etc.)", displayOrder: 9 },
  { name: "Basic Arithmetic", slug: "basic-arithmetic", description: "BODMAS and arithmetic operations", displayOrder: 10 },
  { name: "Decimals", slug: "decimals", description: "Decimal operations", displayOrder: 11 },
  { name: "Mental Multiplication", slug: "mental-multiplication", description: "Fast mental multiplication tricks", displayOrder: 12 },
  { name: "Mental Division", slug: "mental-division", description: "Fast mental division tricks", displayOrder: 13 },
  { name: "Age Problems", slug: "age-problems", description: "Age-based word problems", displayOrder: 14 },
  { name: "Time Calculation", slug: "time-calculation", description: "Time differences and clock problems", displayOrder: 15 },
  { name: "Relative Speed", slug: "relative-speed", description: "Relative speed and trains/boats", displayOrder: 16 },
  { name: "Number Patterns", slug: "number-patterns", description: "Number series and patterns", displayOrder: 17 },
  { name: "Mixed Mental Math", slug: "mixed-mental-math", description: "Mixed mental math problems", displayOrder: 18 },
];

// All 50 questions verified mathematically
const QUESTIONS = [
  {
    text: "A car runs at a speed of 90 km/h. How many kilometers will it cover in 20 minutes?",
    correctAnswer: "30",
    acceptedAnswers: ["30", "30 km", "30km"],
    unit: "km",
    categorySlug: "speed-distance-time",
    difficulty: "Easy",
    shortcut: "20 minutes = 1/3 of an hour. 90 ÷ 3 = 30.",
    explanation: "Distance = Speed × Time. 20 minutes is 1/3 hour, so 90 × 1/3 = 30 km.",
    mentalPattern: "Convert minutes into a simple fraction of an hour, then multiply.",
    commonMistake: "Multiplying 90 by 20 instead of converting minutes to hours.",
    patternKey: "speed_distance_minutes",
  },
  {
    text: "What is 15% of 240?",
    correctAnswer: "36",
    acceptedAnswers: ["36"],
    unit: null,
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "10% of 240 = 24, 5% = 12, therefore 24 + 12 = 36.",
    explanation: "15% = 10% + 5%. 10% of 240 = 24, and 5% of 240 = 12. Total = 36.",
    mentalPattern: "15% = 10% + 5%. Break percentage into manageable chunks.",
    commonMistake: "Multiplying 240 × 0.15 directly in long form.",
    patternKey: "percentage_basic",
  },
  {
    text: "A pole is 60 meters long. If 1/4 of it is inside the mud, how many meters are outside the mud?",
    correctAnswer: "45",
    acceptedAnswers: ["45", "45 m", "45m"],
    unit: "m",
    categorySlug: "fractions",
    difficulty: "Easy",
    shortcut: "1/4 of 60 = 15, so 60 - 15 = 45.",
    explanation: "1/4 of 60 = 15. Outside = 60 - 15 = 45 meters.",
    mentalPattern: "Find the part you know, then subtract from the whole.",
    commonMistake: "Subtracting 1/4 from 60 incorrectly as 60 - 4.",
    patternKey: "fraction_remaining",
  },
  {
    text: "If 12 eggs cost 120, what is the price of 5 eggs?",
    correctAnswer: "50",
    acceptedAnswers: ["50"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Easy",
    shortcut: "1 egg = 10, therefore 5 eggs = 50.",
    explanation: "Unit price = 120 ÷ 12 = 10. So 5 eggs = 5 × 10 = 50.",
    mentalPattern: "Find the unit price first, then multiply.",
    commonMistake: "Multiplying 120 × 5/12 incorrectly.",
    patternKey: "unit_price",
  },
  {
    text: "An airplane flies at 600 km/h. How many kilometers does it cover in 6 minutes?",
    correctAnswer: "60",
    acceptedAnswers: ["60", "60 km", "60km"],
    unit: "km",
    categorySlug: "speed-distance-time",
    difficulty: "Easy",
    shortcut: "6 minutes = 1/10 hour, so 600 ÷ 10 = 60.",
    explanation: "6 minutes = 6/60 = 1/10 hour. Distance = 600 × 1/10 = 60 km.",
    mentalPattern: "Convert short times into simple fractions of an hour.",
    commonMistake: "Forgetting to convert minutes to hours.",
    patternKey: "speed_distance_minutes",
  },
  {
    text: "Which fraction is the biggest: 5/6, 6/7, 7/8, or 3/4?",
    correctAnswer: "7/8",
    acceptedAnswers: ["7/8"],
    unit: null,
    categorySlug: "fractions",
    difficulty: "Medium",
    shortcut: "For fractions where numerator is one less than denominator, the larger denominator produces the larger fraction.",
    explanation: "Among 5/6, 6/7, 7/8, each is (n-1)/n. The fraction gets closer to 1 as n grows. 7/8 = 0.875, the largest.",
    mentalPattern: "Fractions of the form (n-1)/n increase as n increases.",
    commonMistake: "Comparing denominators without considering the relationship between numerator and denominator.",
    patternKey: "fraction_compare",
  },
  {
    text: "A student gets 450 marks out of 600. What is his percentage?",
    correctAnswer: "75",
    acceptedAnswers: ["75", "75%"],
    unit: "%",
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "450/600 = 3/4 = 75%.",
    explanation: "450/600 simplifies to 3/4, which equals 75%.",
    mentalPattern: "Simplify the fraction first, then convert to percentage.",
    commonMistake: "Long division of 450 ÷ 600.",
    patternKey: "percentage_basic",
  },
  {
    text: "A man buys a shirt for 400 and sells it for 500. What is his profit percentage?",
    correctAnswer: "25",
    acceptedAnswers: ["25", "25%"],
    unit: "%",
    categorySlug: "profit-loss",
    difficulty: "Easy",
    shortcut: "Profit = 100. 100/400 = 25%.",
    explanation: "Profit = 500 - 400 = 100. Profit % = (100/400) × 100 = 25%.",
    mentalPattern: "Profit % is always on cost price, not selling price.",
    commonMistake: "Calculating 100/500 instead of 100/400.",
    patternKey: "profit_percentage",
  },
  {
    text: "Two trains are 300 km apart. They move toward each other at speeds of 70 km/h and 80 km/h. After how many hours will they meet?",
    correctAnswer: "2",
    acceptedAnswers: ["2", "2 hours", "2 hours", "2h"],
    unit: "hours",
    categorySlug: "speed-distance-time",
    difficulty: "Medium",
    shortcut: "Add speeds: 70 + 80 = 150. 300 ÷ 150 = 2.",
    explanation: "Relative speed = 70 + 80 = 150 km/h. Time = 300 ÷ 150 = 2 hours.",
    mentalPattern: "Objects moving toward each other: add their speeds.",
    commonMistake: "Subtracting the speeds instead of adding.",
    patternKey: "relative_speed_meet",
  },
  {
    text: "Solve: 16 - 4 × 3 + 2.",
    correctAnswer: "6",
    acceptedAnswers: ["6"],
    unit: null,
    categorySlug: "basic-arithmetic",
    difficulty: "Easy",
    shortcut: "Multiplication first: 4 × 3 = 12. Then 16 - 12 + 2 = 6.",
    explanation: "BODMAS: 4 × 3 = 12. Then 16 - 12 + 2 = 6.",
    mentalPattern: "BODMAS: multiplication before addition and subtraction.",
    commonMistake: "Doing operations left to right (16 - 4 = 12, then 12 × 3 = 36).",
    patternKey: "bodmas",
  },
  {
    text: "A car uses 10 liters of petrol to travel 120 km. How many liters does it need for 300 km?",
    correctAnswer: "25",
    acceptedAnswers: ["25", "25 L", "25L", "25 liters"],
    unit: "L",
    categorySlug: "ratios-proportions",
    difficulty: "Medium",
    shortcut: "300/120 = 2.5, therefore 10 × 2.5 = 25.",
    explanation: "Rate = 10 L per 120 km = 1/12 L per km. For 300 km: 300 × (1/12) = 25 L.",
    mentalPattern: "Find rate per unit, then scale.",
    commonMistake: "Setting up ratio incorrectly.",
    patternKey: "unit_consumption",
  },
  {
    text: "A father is 4 times older than his son. The sum of their ages is 45 years. What is the age of the son?",
    correctAnswer: "9",
    acceptedAnswers: ["9", "9 years", "9 yrs", "9y"],
    unit: "years",
    categorySlug: "age-problems",
    difficulty: "Medium",
    shortcut: "4 + 1 = 5 parts. 45 ÷ 5 = 9.",
    explanation: "Let son's age = x, father's = 4x. x + 4x = 45, so 5x = 45, x = 9.",
    mentalPattern: "Convert ratio into total parts, then divide.",
    commonMistake: "Dividing 45 by 4 instead of 5.",
    patternKey: "age_ratio",
  },
  {
    text: "Pipe A fills a tank in 4 hours, and Pipe B fills it in 12 hours. If both pipes are open together, how many hours will they take to fill the tank?",
    correctAnswer: "3",
    acceptedAnswers: ["3", "3 hours", "3h"],
    unit: "hours",
    categorySlug: "pipes-tanks",
    difficulty: "Hard",
    shortcut: "Product over sum: (4 × 12)/(4 + 12) = 48/16 = 3.",
    explanation: "Combined rate = 1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3 per hour. Time = 3 hours.",
    mentalPattern: "For two pipes, time = (a × b)/(a + b).",
    commonMistake: "Averaging the times: (4 + 12)/2 = 8.",
    patternKey: "pipes_combined",
  },
  {
    text: "What is 35% of 80?",
    correctAnswer: "28",
    acceptedAnswers: ["28"],
    unit: null,
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "30% = 24 and 5% = 4, total = 28.",
    explanation: "35% = 30% + 5%. 30% of 80 = 24. 5% of 80 = 4. Total = 28.",
    mentalPattern: "Break percentage into 10%, 5%, 1% chunks.",
    commonMistake: "Long multiplication.",
    patternKey: "percentage_basic",
  },
  {
    text: "A plane travels 180 km in 15 minutes. What is its speed in km/h?",
    correctAnswer: "720",
    acceptedAnswers: ["720", "720 km/h", "720km/h"],
    unit: "km/h",
    categorySlug: "speed-distance-time",
    difficulty: "Medium",
    shortcut: "15 minutes = 1/4 hour, so multiply 180 × 4 = 720.",
    explanation: "Speed = Distance/Time. Time = 15 min = 1/4 hr. Speed = 180/(1/4) = 180 × 4 = 720 km/h.",
    mentalPattern: "Convert minutes to hour fraction, then divide or multiply accordingly.",
    commonMistake: "Dividing 180 by 15 instead of converting to hours.",
    patternKey: "speed_distance_minutes",
  },
  {
    text: "A 150-meter-long train is moving at 54 km/h. How many seconds will it take to pass a pole?",
    correctAnswer: "10",
    acceptedAnswers: ["10", "10 s", "10s", "10 sec", "10 sec", "10 seconds"],
    unit: "s",
    categorySlug: "unit-conversion",
    difficulty: "Hard",
    shortcut: "54 km/h = 15 m/s. 150 ÷ 15 = 10.",
    explanation: "Convert 54 km/h to m/s: 54 × (5/18) = 15 m/s. Time = 150 ÷ 15 = 10 s.",
    mentalPattern: "To pass a pole, distance = train length. km/h to m/s: × 5/18.",
    commonMistake: "Forgetting to convert km/h to m/s.",
    patternKey: "train_pole",
  },
  {
    text: "The average score of 4 tests is 70. How many marks are needed in the 5th test to make the total average 74?",
    correctAnswer: "90",
    acceptedAnswers: ["90"],
    unit: null,
    categorySlug: "averages",
    difficulty: "Hard",
    shortcut: "Target average rises by 4 across 5 tests. Required extra = 4 × 5 = 20 above average 70, giving 90.",
    explanation: "Total needed for avg 74 over 5 tests = 74 × 5 = 370. Already have 70 × 4 = 280. Need 370 - 280 = 90.",
    mentalPattern: "Total = Average × Number. Required = New total - Existing total.",
    commonMistake: "Multiplying 4 × 4 instead of 5 × 4.",
    patternKey: "average_target",
  },
  {
    text: "Divide: 0.4 ÷ 0.02.",
    correctAnswer: "20",
    acceptedAnswers: ["20"],
    unit: null,
    categorySlug: "decimals",
    difficulty: "Easy",
    shortcut: "Move both decimals two places: 40 ÷ 2 = 20.",
    explanation: "Multiply numerator and denominator by 100: 40/2 = 20.",
    mentalPattern: "To divide decimals, shift both to whole numbers.",
    commonMistake: "Dividing 0.4 by 0.02 incorrectly.",
    patternKey: "decimal_division",
  },
  {
    text: "The price of an item is 850. If you get a 20% discount, what is the final price?",
    correctAnswer: "680",
    acceptedAnswers: ["680"],
    unit: null,
    categorySlug: "profit-loss",
    difficulty: "Easy",
    shortcut: "20% of 850 = 170. 850 - 170 = 680.",
    explanation: "Discount = 20% × 850 = 170. Final price = 850 - 170 = 680.",
    mentalPattern: "Discount amount = percentage × original. Final = original - discount.",
    commonMistake: "Calculating 20% of 850 incorrectly.",
    patternKey: "discount",
  },
  {
    text: "A bamboo stick is 90 meters long. 1/3 is in water, 1/6 is in mud, and the rest is in the air. How many meters are in the air?",
    correctAnswer: "45",
    acceptedAnswers: ["45", "45 m", "45m"],
    unit: "m",
    categorySlug: "fractions",
    difficulty: "Medium",
    shortcut: "1/3 + 1/6 = 1/2. Half of 90 = 45.",
    explanation: "1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2. So 1/2 is in water/mud, and 1/2 is in air = 45 m.",
    mentalPattern: "Add fractions with common denominator first.",
    commonMistake: "Adding 1/3 + 1/6 as 2/9.",
    patternKey: "fraction_remaining",
  },
  {
    text: "A car moves at 72 km/h. Change this speed into meters per second.",
    correctAnswer: "20",
    acceptedAnswers: ["20", "20 m/s", "20m/s"],
    unit: "m/s",
    categorySlug: "unit-conversion",
    difficulty: "Medium",
    shortcut: "72 ÷ 18 × 5 = 20.",
    explanation: "km/h to m/s: multiply by 5/18. 72 × 5/18 = 72/18 × 5 = 4 × 5 = 20 m/s.",
    mentalPattern: "km/h to m/s: × 5/18. Common: 18 km/h = 5 m/s, 36 = 10, 54 = 15, 72 = 20.",
    commonMistake: "Multiplying by 18/5 instead of 5/18.",
    patternKey: "unit_speed",
  },
  {
    text: "8 men can finish a work in 15 days. How many days will 12 men take to finish the same work?",
    correctAnswer: "10",
    acceptedAnswers: ["10", "10 days", "10d"],
    unit: "days",
    categorySlug: "work-time",
    difficulty: "Medium",
    shortcut: "Total work = 8 × 15 = 120 man-days. 120 ÷ 12 = 10.",
    explanation: "Work = men × days = 8 × 15 = 120. Days = 120/12 = 10.",
    mentalPattern: "Man-days: total work is constant. More men = fewer days.",
    commonMistake: "Cross-multiplying incorrectly.",
    patternKey: "man_days",
  },
  {
    text: "The distance between two cities is 260 km. A bus leaves at 8:00 AM at a speed of 65 km/h. At what time will it arrive?",
    correctAnswer: "12:00 PM",
    acceptedAnswers: ["12:00 PM", "12 PM", "12:00PM", "12:00 pm", "12:00pm"],
    unit: null,
    categorySlug: "time-calculation",
    difficulty: "Medium",
    shortcut: "260 ÷ 65 = 4 hours. 8 AM + 4 hours = noon.",
    explanation: "Time = 260/65 = 4 hours. 8 AM + 4 hours = 12 PM.",
    mentalPattern: "Time = Distance ÷ Speed. Add to departure time.",
    commonMistake: "Confusing AM/PM.",
    patternKey: "time_arrival",
  },
  {
    text: "What is 7.5% of 200?",
    correctAnswer: "15",
    acceptedAnswers: ["15"],
    unit: null,
    categorySlug: "percentages",
    difficulty: "Medium",
    shortcut: "7.5 × 2 = 15.",
    explanation: "7.5% of 200 = 7.5 × 2 = 15.",
    mentalPattern: "7.5% = 15/2. So percentage × 2 = answer when base is 200.",
    commonMistake: "Long multiplication.",
    patternKey: "percentage_basic",
  },
  {
    text: "A person bought an item for 600 and sold it at a 15% loss. What was the selling price?",
    correctAnswer: "510",
    acceptedAnswers: ["510"],
    unit: null,
    categorySlug: "profit-loss",
    difficulty: "Easy",
    shortcut: "15% of 600 = 90. 600 - 90 = 510.",
    explanation: "Loss = 15% × 600 = 90. Selling price = 600 - 90 = 510.",
    mentalPattern: "Loss amount = percentage × cost. Selling = cost - loss.",
    commonMistake: "Adding 15% instead of subtracting.",
    patternKey: "loss",
  },
  {
    text: "Multiply: 0.05 × 0.6.",
    correctAnswer: "0.03",
    acceptedAnswers: ["0.03", ".03"],
    unit: null,
    categorySlug: "decimals",
    difficulty: "Easy",
    shortcut: "5 × 6 = 30. Three decimal places total → 0.030 = 0.03.",
    explanation: "0.05 × 0.6 = 5 × 6 / 1000 = 30/1000 = 0.03.",
    mentalPattern: "Count decimal places, multiply whole numbers, place decimals back.",
    commonMistake: "Getting 0.30 instead of 0.03.",
    patternKey: "decimal_multiplication",
  },
  {
    text: "If 3 notebooks cost 90, what is the cost of 11 notebooks?",
    correctAnswer: "330",
    acceptedAnswers: ["330"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Easy",
    shortcut: "One notebook = 30. 11 × 30 = 330.",
    explanation: "Unit price = 90/3 = 30. Cost of 11 = 11 × 30 = 330.",
    mentalPattern: "Find unit price, then multiply.",
    commonMistake: "Proportional mistake.",
    patternKey: "unit_price",
  },
  {
    text: "In a class of 48 students, the ratio of boys to girls is 5:3. How many girls are there?",
    correctAnswer: "18",
    acceptedAnswers: ["18"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Medium",
    shortcut: "Total parts = 8. 48 ÷ 8 = 6. Girls = 3 × 6 = 18.",
    explanation: "Total parts = 5 + 3 = 8. Each part = 48/8 = 6. Girls = 3 × 6 = 18.",
    mentalPattern: "Total parts method: sum the ratio, divide total, multiply by desired part.",
    commonMistake: "Confusing which part belongs to girls.",
    patternKey: "ratio_division",
  },
  {
    text: "A boy runs 400 meters in 50 seconds. What is his speed in km/h?",
    correctAnswer: "28.8",
    acceptedAnswers: ["28.8", "28.8 km/h", "28.8km/h"],
    unit: "km/h",
    categorySlug: "unit-conversion",
    difficulty: "Hard",
    shortcut: "400 ÷ 50 = 8 m/s. 8 × 3.6 = 28.8.",
    explanation: "Speed = 400/50 = 8 m/s. To convert to km/h: 8 × 3.6 = 28.8 km/h.",
    mentalPattern: "m/s to km/h: × 3.6. Or × 18/5.",
    commonMistake: "Multiplying by 3.6 incorrectly.",
    patternKey: "unit_speed",
  },
  {
    text: "Solve: 50 - 5 × (4 + 2).",
    correctAnswer: "20",
    acceptedAnswers: ["20"],
    unit: null,
    categorySlug: "basic-arithmetic",
    difficulty: "Easy",
    shortcut: "Bracket first: 6. Then 5 × 6 = 30. 50 - 30 = 20.",
    explanation: "BODMAS: (4+2) = 6. 5 × 6 = 30. 50 - 30 = 20.",
    mentalPattern: "BODMAS: brackets, then orders, then multiplication, then addition/subtraction.",
    commonMistake: "Doing 5 × 4 = 20 first without brackets.",
    patternKey: "bodmas",
  },
  {
    text: "A water tank is 3/5 full. If it needs 30 more liters to become completely full, what is the total capacity of the tank?",
    correctAnswer: "75",
    acceptedAnswers: ["75", "75 L", "75L"],
    unit: "L",
    categorySlug: "fractions",
    difficulty: "Hard",
    shortcut: "Empty = 2/5 = 30 L. Therefore 1/5 = 15 and 5/5 = 75.",
    explanation: "If 3/5 is full, 2/5 is empty = 30 L. So 1/5 = 15 L. Total = 5/5 = 75 L.",
    mentalPattern: "Identify what fraction equals the known amount, then scale.",
    commonMistake: "Dividing 30 by 3 instead of 2.",
    patternKey: "fraction_capacity",
  },
  {
    text: "If 1.5 liters of milk cost 120, what is the price of 4 liters?",
    correctAnswer: "320",
    acceptedAnswers: ["320"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Hard",
    shortcut: "1.5 L = 3 × 0.5 L. 0.5 L = 40. Four liters = 8 × 40 = 320.",
    explanation: "Price per 0.5 L = 120/3 = 40. 4 L = 8 × 0.5 L = 8 × 40 = 320.",
    mentalPattern: "Break the problem into smaller equal units.",
    commonMistake: "Direct proportion error.",
    patternKey: "unit_price",
  },
  {
    text: "A truck travels for 2 hours at 45 km/h, and then for 2 hours at 75 km/h. What is its average speed?",
    correctAnswer: "60",
    acceptedAnswers: ["60", "60 km/h", "60km/h"],
    unit: "km/h",
    categorySlug: "averages",
    difficulty: "Medium",
    shortcut: "Equal travel times → average of speeds: (45 + 75)/2 = 60.",
    explanation: "When time is equal, average speed = (v1 + v2)/2 = (45 + 75)/2 = 60.",
    mentalPattern: "Equal times: simple average of speeds. Equal distances: harmonic mean.",
    commonMistake: "Using total distance / total time incorrectly.",
    patternKey: "average_speed",
  },
  {
    text: "What is 250% of 40?",
    correctAnswer: "100",
    acceptedAnswers: ["100"],
    unit: null,
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "200% = 80, 50% = 20, total = 100.",
    explanation: "250% = 2.5 × 40 = 100. Or: 200% + 50% = 80 + 20 = 100.",
    mentalPattern: "Percentages above 100 mean multiplying by more than 1.",
    commonMistake: "Confusing 250% with 25%.",
    patternKey: "percentage_basic",
  },
  {
    text: "The average of 5 consecutive odd numbers is 27. What is the largest number among them?",
    correctAnswer: "31",
    acceptedAnswers: ["31"],
    unit: null,
    categorySlug: "number-patterns",
    difficulty: "Hard",
    shortcut: "Average is middle number. Sequence = 23, 25, 27, 29, 31.",
    explanation: "For odd count of consecutive numbers, average = middle. Middle = 27. Sequence: 23, 25, 27, 29, 31.",
    mentalPattern: "Average of consecutive numbers = middle number (when count is odd).",
    commonMistake: "Not recognizing the middle number rule.",
    patternKey: "consecutive_odd",
  },
  {
    text: "You buy an item for 80 and sell it for 100. What is your profit percentage?",
    correctAnswer: "25",
    acceptedAnswers: ["25", "25%"],
    unit: "%",
    categorySlug: "profit-loss",
    difficulty: "Easy",
    shortcut: "Profit = 20. 20/80 = 1/4 = 25%.",
    explanation: "Profit = 100 - 80 = 20. Profit % = (20/80) × 100 = 25%.",
    mentalPattern: "Profit % = (Profit/Cost) × 100.",
    commonMistake: "Calculating 20/100 instead of 20/80.",
    patternKey: "profit_percentage",
  },
  {
    text: "A boat moves downstream at 24 km/h and upstream at 16 km/h. What is the speed of the water stream?",
    correctAnswer: "4",
    acceptedAnswers: ["4", "4 km/h", "4km/h"],
    unit: "km/h",
    categorySlug: "relative-speed",
    difficulty: "Hard",
    shortcut: "(24 - 16)/2 = 4.",
    explanation: "Stream speed = (downstream - upstream)/2 = (24 - 16)/2 = 4 km/h.",
    mentalPattern: "Stream speed is half the difference of downstream and upstream speeds.",
    commonMistake: "Averaging the speeds instead of halving the difference.",
    patternKey: "boat_stream",
  },
  {
    text: "Person A can do a task in 10 days, and Person B can do it in 15 days. In how many days can they complete it together?",
    correctAnswer: "6",
    acceptedAnswers: ["6", "6 days", "6d"],
    unit: "days",
    categorySlug: "work-time",
    difficulty: "Hard",
    shortcut: "Product over sum = (10 × 15)/(10 + 15) = 150/25 = 6.",
    explanation: "Combined rate = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6. Time = 6 days.",
    mentalPattern: "Combined work = sum of individual rates. For two people: (a × b)/(a + b).",
    commonMistake: "Averaging the days: (10 + 15)/2 = 12.5.",
    patternKey: "work_together",
  },
  {
    text: "What is 12.5% of 800?",
    correctAnswer: "100",
    acceptedAnswers: ["100"],
    unit: null,
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "12.5% = 1/8. 800 ÷ 8 = 100.",
    explanation: "12.5% = 1/8. 800 × 1/8 = 100.",
    mentalPattern: "Memorize: 12.5% = 1/8, 25% = 1/4, 50% = 1/2, 75% = 3/4.",
    commonMistake: "Converting 12.5% to a fraction incorrectly.",
    patternKey: "percentage_basic",
  },
  {
    text: "How many total minutes are there from 9:45 AM to 1:15 PM?",
    correctAnswer: "210",
    acceptedAnswers: ["210", "210 min", "210 minutes"],
    unit: "min",
    categorySlug: "time-calculation",
    difficulty: "Medium",
    shortcut: "9:45 to 1:45 = 240 minutes. Subtract 30 = 210.",
    explanation: "9:45 AM to 1:45 PM = 4 hours = 240 min. Subtract 30 min (to 1:15 PM) = 210 min.",
    mentalPattern: "Round to a friendly time, then adjust.",
    commonMistake: "Forgetting AM to PM conversion adds 12 hours context.",
    patternKey: "time_difference",
  },
  {
    text: "A car increases its speed from 40 km/h to 60 km/h. What is the percentage increase in speed?",
    correctAnswer: "50",
    acceptedAnswers: ["50", "50%"],
    unit: "%",
    categorySlug: "percentages",
    difficulty: "Easy",
    shortcut: "Increase = 20. 20/40 = 1/2 = 50%.",
    explanation: "% increase = (20/40) × 100 = 50%.",
    mentalPattern: "% change = (change/original) × 100.",
    commonMistake: "Dividing by the new value (60) instead of the original (40).",
    patternKey: "percentage_increase",
  },
  {
    text: "Solve: 3/4 - 2/5.",
    correctAnswer: "7/20",
    acceptedAnswers: ["7/20", "0.35"],
    unit: null,
    categorySlug: "fractions",
    difficulty: "Medium",
    shortcut: "Cross multiply: 3×5 - 2×4 = 15 - 8 = 7. Denominator = 20.",
    explanation: "Common denominator 20. 3/4 = 15/20, 2/5 = 8/20. 15/20 - 8/20 = 7/20.",
    mentalPattern: "Butterfly method: cross-multiply to subtract fractions.",
    commonMistake: "Subtracting denominators instead of finding common denominator.",
    patternKey: "fraction_subtraction",
  },
  {
    text: "A train 200 meters long runs at 72 km/h. How many seconds will it take to cross a 300-meter-long bridge?",
    correctAnswer: "25",
    acceptedAnswers: ["25", "25 s", "25s", "25 sec", "25 seconds"],
    unit: "s",
    categorySlug: "relative-speed",
    difficulty: "Hard",
    shortcut: "Total distance = 200 + 300 = 500 m. 72 km/h = 20 m/s. 500 ÷ 20 = 25.",
    explanation: "Total distance = train + bridge = 500 m. 72 km/h = 20 m/s. Time = 500/20 = 25 s.",
    mentalPattern: "To cross a platform/bridge: add lengths. km/h to m/s: × 5/18.",
    commonMistake: "Forgetting to add bridge length to train length.",
    patternKey: "train_bridge",
  },
  {
    text: "If 5 apples cost 45, how many apples can you buy for 117?",
    correctAnswer: "13",
    acceptedAnswers: ["13", "13 apples"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Medium",
    shortcut: "One apple = 9. 117 ÷ 9 = 13.",
    explanation: "Unit price = 45/5 = 9. Apples = 117/9 = 13.",
    mentalPattern: "Find unit price, then divide budget by unit price.",
    commonMistake: "Direct proportion error.",
    patternKey: "unit_price",
  },
  {
    text: "Two cyclists start from the same point and move in opposite directions at 14 km/h and 18 km/h. How far apart will they be after 30 minutes?",
    correctAnswer: "16",
    acceptedAnswers: ["16", "16 km", "16km"],
    unit: "km",
    categorySlug: "relative-speed",
    difficulty: "Hard",
    shortcut: "Opposite directions → add speeds = 32 km/h. Half hour → 16 km.",
    explanation: "Relative speed = 14 + 18 = 32 km/h. In 0.5 hours: 32 × 0.5 = 16 km.",
    mentalPattern: "Opposite direction: add speeds. Time in hours = minutes/60.",
    commonMistake: "Subtracting speeds instead of adding.",
    patternKey: "opposite_direction",
  },
  {
    text: "Find the average of these four numbers: 14, 22, 34, and 50.",
    correctAnswer: "30",
    acceptedAnswers: ["30"],
    unit: null,
    categorySlug: "averages",
    difficulty: "Easy",
    shortcut: "Sum = 120. 120 ÷ 4 = 30.",
    explanation: "Sum = 14 + 22 + 34 + 50 = 120. Average = 120/4 = 30.",
    mentalPattern: "Average = sum/count.",
    commonMistake: "Forgetting one number.",
    patternKey: "average_basic",
  },
  {
    text: "A rope 84 cm long is divided into two pieces in the ratio 4:3. What is the length of the larger piece?",
    correctAnswer: "48",
    acceptedAnswers: ["48", "48 cm", "48cm"],
    unit: "cm",
    categorySlug: "ratios-proportions",
    difficulty: "Medium",
    shortcut: "Total parts = 7. 84 ÷ 7 = 12. Larger = 4 × 12 = 48.",
    explanation: "Total parts = 4 + 3 = 7. Each part = 84/7 = 12. Larger = 4 × 12 = 48.",
    mentalPattern: "Total parts method: sum ratio, find unit, multiply.",
    commonMistake: "Confusing larger and smaller parts.",
    patternKey: "ratio_division",
  },
  {
    text: "An aircraft goes up at a speed of 450 meters per minute. How high will it go in 4 minutes and 20 seconds?",
    correctAnswer: "1950",
    acceptedAnswers: ["1950", "1950 m", "1950m"],
    unit: "m",
    categorySlug: "speed-distance-time",
    difficulty: "Hard",
    shortcut: "20 seconds = 1/3 minute. 4 minutes = 1800 m, plus 150 m = 1950 m.",
    explanation: "4 min 20 sec = 4 + 20/60 = 4 + 1/3 = 13/3 min. Distance = 450 × 13/3 = 1950 m.",
    mentalPattern: "Convert everything to consistent unit, then multiply.",
    commonMistake: "Treating 4 min 20 sec as 4.20 min.",
    patternKey: "time_mixed",
  },
  {
    text: "Multiply quickly: 45 × 11.",
    correctAnswer: "495",
    acceptedAnswers: ["495"],
    unit: null,
    categorySlug: "mental-multiplication",
    difficulty: "Easy",
    shortcut: "Put the sum of the digits between them: 4 + 5 = 9 → 495.",
    explanation: "For 2-digit × 11: add the digits and place between. 4_(4+5)_5 = 4_9_5 = 495.",
    mentalPattern: "Two-digit × 11: add digits and place between them.",
    commonMistake: "Carrying over when sum of digits ≥ 10 incorrectly.",
    patternKey: "multiply_by_11",
  },
  {
    text: "If 12 pens cost 72, how much will 20 pens cost?",
    correctAnswer: "120",
    acceptedAnswers: ["120"],
    unit: null,
    categorySlug: "ratios-proportions",
    difficulty: "Easy",
    shortcut: "One pen = 6. 20 × 6 = 120.",
    explanation: "Unit price = 72/12 = 6. Cost of 20 = 20 × 6 = 120.",
    mentalPattern: "Unit price × quantity = total cost.",
    commonMistake: "Proportion cross-multiplication error.",
    patternKey: "unit_price",
  },
];

// Mental Math Patterns library
const PATTERNS = [
  {
    title: "Percentage Shortcuts",
    category: "Percentages",
    description: "Memorize these common percentage equivalences to compute faster.",
    examples: JSON.stringify([
      "10% rule: move decimal one place",
      "5% rule: half of 10%",
      "12.5% = 1/8",
      "25% = 1/4",
      "50% = 1/2",
      "75% = 3/4",
      "20% = 1/5",
      "33.33% = 1/3",
      "15% = 10% + 5%",
      "35% = 30% + 5%",
    ]),
    formula: "Percentage = (Part/Whole) × 100",
  },
  {
    title: "Speed Conversion: km/h ↔ m/s",
    category: "Speed, Distance & Time",
    description: "Quick conversion between common units of speed.",
    examples: JSON.stringify([
      "18 km/h = 5 m/s",
      "36 km/h = 10 m/s",
      "54 km/h = 15 m/s",
      "72 km/h = 20 m/s",
      "90 km/h = 25 m/s",
      "108 km/h = 30 m/s",
    ]),
    formula: "km/h × (5/18) = m/s; m/s × (18/5) = km/h",
  },
  {
    title: "Time as Fraction of Hour",
    category: "Time Calculation",
    description: "Convert minutes to fraction of hour for speed/distance problems.",
    examples: JSON.stringify([
      "15 min = 1/4 hour",
      "20 min = 1/3 hour",
      "30 min = 1/2 hour",
      "6 min = 1/10 hour",
      "10 min = 1/6 hour",
      "45 min = 3/4 hour",
    ]),
    formula: "minutes/60 = fraction of hour",
  },
  {
    title: "Total Parts Method (Ratio)",
    category: "Ratios & Proportions",
    description: "Add ratio parts to find total, then divide to get unit value.",
    examples: JSON.stringify([
      "Ratio 5:3, total 8 parts",
      "Sum total = 48",
      "Each part = 48/8 = 6",
      "Bigger = 5×6 = 30, smaller = 3×6 = 18",
    ]),
    formula: "Unit value = Total / (Sum of ratio parts)",
  },
  {
    title: "Man-Days (Work & Time)",
    category: "Work & Time",
    description: "Total work is constant; more workers means fewer days.",
    examples: JSON.stringify([
      "8 men × 15 days = 120 man-days of work",
      "12 men × ? = 120",
      "Days = 120/12 = 10",
    ]),
    formula: "Work = Men × Days",
  },
  {
    title: "Pipes & Tanks (Product Over Sum)",
    category: "Pipes & Tanks",
    description: "For two independent filling pipes, time = (a × b)/(a + b).",
    examples: JSON.stringify([
      "Pipe A: 4 hours, Pipe B: 12 hours",
      "Together: (4×12)/(4+12) = 48/16 = 3 hours",
    ]),
    formula: "Time = (a × b) / (a + b)",
  },
  {
    title: "Profit & Loss Percentage",
    category: "Profit & Loss",
    description: "Profit/Loss is always calculated on cost price, not selling price.",
    examples: JSON.stringify([
      "Cost = 400, Sell = 500, Profit = 100",
      "Profit % = 100/400 = 25%",
    ]),
    formula: "Profit % = (Profit / Cost) × 100",
  },
  {
    title: "Discount",
    category: "Profit & Loss",
    description: "Final price after a discount.",
    examples: JSON.stringify([
      "Price 850, discount 20%",
      "Discount = 20% of 850 = 170",
      "Final = 850 - 170 = 680",
    ]),
    formula: "Final = Original - (Discount% × Original)",
  },
  {
    title: "Average",
    category: "Averages",
    description: "Mean of a set of numbers.",
    examples: JSON.stringify([
      "14, 22, 34, 50 → sum 120, count 4, average 30",
    ]),
    formula: "Average = Sum / Count",
  },
  {
    title: "Fraction Subtraction (Butterfly)",
    category: "Fractions",
    description: "Cross-multiply to subtract fractions quickly.",
    examples: JSON.stringify([
      "3/4 - 2/5: (3×5 - 2×4) / (4×5) = (15-8)/20 = 7/20",
    ]),
    formula: "a/b - c/d = (ad - bc) / (bd)",
  },
  {
    title: "Multiply by 11",
    category: "Mental Multiplication",
    description: "For 2-digit number × 11, place the digit sum between the digits.",
    examples: JSON.stringify([
      "45 × 11: split 4 and 5, sum = 9, place between → 495",
      "67 × 11: sum = 13, carry: 7_13 becomes 7+1=8, 3, last 7 → 737",
    ]),
    formula: "ab × 11 = a(a+b)b, with carry if a+b ≥ 10",
  },
  {
    title: "Train Crossing a Pole",
    category: "Speed, Distance & Time",
    description: "When a train passes a pole, distance = train length only.",
    examples: JSON.stringify([
      "Train 150m, speed 54 km/h = 15 m/s",
      "Time = 150/15 = 10 s",
    ]),
    formula: "Time = Length / Speed (in consistent units)",
  },
  {
    title: "Train Crossing a Bridge",
    category: "Speed, Distance & Time",
    description: "When a train crosses a bridge, total distance = train + bridge length.",
    examples: JSON.stringify([
      "Train 200m, bridge 300m, speed 72 km/h = 20 m/s",
      "Time = (200+300)/20 = 25 s",
    ]),
    formula: "Time = (Train + Bridge) / Speed",
  },
  {
    title: "Boats & Streams",
    category: "Speed, Distance & Time",
    description: "Downstream speed = boat + stream; Upstream = boat - stream.",
    examples: JSON.stringify([
      "Down 24, Up 16. Stream = (24-16)/2 = 4 km/h. Boat = (24+16)/2 = 20 km/h",
    ]),
    formula: "Stream = (Down - Up)/2; Boat = (Down + Up)/2",
  },
  {
    title: "Opposite Direction",
    category: "Speed, Distance & Time",
    description: "When two objects move in opposite directions, their relative speed is the sum.",
    examples: JSON.stringify([
      "14 km/h and 18 km/h opposite → 32 km/h apart",
      "In 30 min: 32 × 0.5 = 16 km",
    ]),
    formula: "Relative speed = Sum of individual speeds",
  },
  {
    title: "BODMAS Order",
    category: "Basic Arithmetic",
    description: "Order of operations: Brackets, Orders, Division/Multiplication, Addition/Subtraction.",
    examples: JSON.stringify([
      "16 - 4 × 3 + 2 = 16 - 12 + 2 = 6",
      "50 - 5 × (4+2) = 50 - 5×6 = 50 - 30 = 20",
    ]),
    formula: "B > O > D/M > A/S",
  },
];

async function main() {
  console.log("Starting seed...");

  // Clear existing data
  await prisma.questionAttempt.deleteMany();
  await prisma.quizQuestion.deleteMany();
  await prisma.quizSession.deleteMany();
  await prisma.userPerformance.deleteMany();
  await prisma.dailyProgress.deleteMany();
  await prisma.question.deleteMany();
  await prisma.category.deleteMany();
  await prisma.mentalPattern.deleteMany();

  // Create categories
  console.log("Creating categories...");
  const categoryMap: Record<string, string> = {};
  for (const cat of CATEGORIES) {
    const created = await prisma.category.create({ data: cat });
    categoryMap[cat.slug] = created.id;
  }

  // Create questions
  console.log("Creating questions...");
  for (const q of QUESTIONS) {
    const categoryId = categoryMap[q.categorySlug];
    if (!categoryId) {
      console.warn(`Missing category: ${q.categorySlug}`);
      continue;
    }
    await prisma.question.create({
      data: {
        text: q.text,
        correctAnswer: q.correctAnswer,
        acceptedAnswers: JSON.stringify(q.acceptedAnswers),
        unit: q.unit,
        categoryId,
        difficulty: q.difficulty,
        shortcut: q.shortcut,
        explanation: q.explanation,
        mentalPattern: q.mentalPattern,
        commonMistake: q.commonMistake,
        sourceType: "seed",
        patternKey: q.patternKey,
      },
    });
  }

  // Create mental patterns
  console.log("Creating mental patterns library...");
  for (const p of PATTERNS) {
    await prisma.mentalPattern.create({ data: p });
  }

  console.log("Seed complete!");
  console.log(`  Categories: ${CATEGORIES.length}`);
  console.log(`  Questions: ${QUESTIONS.length}`);
  console.log(`  Patterns: ${PATTERNS.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
