plugins {
    id 'com.android.application'
}

android {
    namespace "com.iscsp.mentalmatharena"
    compileSdk 34

    defaultConfig {
        applicationId "com.iscsp.mentalmatharena"
        minSdk 21
        targetSdk 34
        versionCode 4
        versionName "1.2.0"
    }

    signingConfigs {
        release {
            storeFile file("../release.keystore")
            storePassword (System.getenv("KS_PASS") ?: "mentalmath")
            keyAlias (System.getenv("KS_ALIAS") ?: "iscspmatharena")
            keyPassword (System.getenv("KS_PASS") ?: "mentalmath")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.google.android.material:material:1.12.0'
}
