package com.iscsp.mentalmatharena;

/**
 * Build-time AdMob constants.
 *
 * The values come from Gradle (see the buildConfigField entries in
 * app/build.gradle), so the ad unit IDs and the App ID in
 * AndroidManifest.xml are always switched together and can never drift
 * apart. The default build uses Google's official TEST ad units; a
 * production build is made with:
 *
 *   ./gradlew assembleRelease -PAD_TEST=0
 *
 * Previously this class was generated by build-offline.sh into its own
 * build directory. Keeping it in the source tree means the app compiles
 * under a normal Gradle build as well.
 */
public final class AdMobConfig {

    private AdMobConfig() {}

    public static final String BANNER_AD_UNIT_ID = BuildConfig.AD_BANNER_ID;
    public static final String INTERSTITIAL_AD_UNIT_ID = BuildConfig.AD_INTERSTITIAL_ID;
    public static final boolean TEST_ADS = BuildConfig.AD_TEST;
}
